namespace GDNative
{
    [NativeTypeName("unsigned int")]
    public enum GDNativeVariantOperator : uint
    {
        GDNATIVE_VARIANT_OP_EQUAL,
        GDNATIVE_VARIANT_OP_NOT_EQUAL,
        GDNATIVE_VARIANT_OP_LESS,
        GDNATIVE_VARIANT_OP_LESS_EQUAL,
        GDNATIVE_VARIANT_OP_GREATER,
        GDNATIVE_VARIANT_OP_GREATER_EQUAL,
        GDNATIVE_VARIANT_OP_ADD,
        GDNATIVE_VARIANT_OP_SUBTRACT,
        GDNATIVE_VARIANT_OP_MULTIPLY,
        GDNATIVE_VARIANT_OP_DIVIDE,
        GDNATIVE_VARIANT_OP_NEGATE,
        GDNATIVE_VARIANT_OP_POSITIVE,
        GDNATIVE_VARIANT_OP_MODULE,
        GDNATIVE_VARIANT_OP_POWER,
        GDNATIVE_VARIANT_OP_SHIFT_LEFT,
        GDNATIVE_VARIANT_OP_SHIFT_RIGHT,
        GDNATIVE_VARIANT_OP_BIT_AND,
        GDNATIVE_VARIANT_OP_BIT_OR,
        GDNATIVE_VARIANT_OP_BIT_XOR,
        GDNATIVE_VARIANT_OP_BIT_NEGATE,
        GDNATIVE_VARIANT_OP_AND,
        GDNATIVE_VARIANT_OP_OR,
        GDNATIVE_VARIANT_OP_XOR,
        GDNATIVE_VARIANT_OP_NOT,
        GDNATIVE_VARIANT_OP_IN,
        GDNATIVE_VARIANT_OP_MAX,
    }
}
