namespace GDNative
{
    [NativeTypeName("unsigned int")]
    public enum GDNativeExtensionClassMethodFlags : uint
    {
        GDNATIVE_EXTENSION_METHOD_FLAG_NORMAL = 1,
        GDNATIVE_EXTENSION_METHOD_FLAG_EDITOR = 2,
        GDNATIVE_EXTENSION_METHOD_FLAG_NOSCRIPT = 4,
        GDNATIVE_EXTENSION_METHOD_FLAG_CONST = 8,
        GDNATIVE_EXTENSION_METHOD_FLAG_REVERSE = 16,
        GDNATIVE_EXTENSION_METHOD_FLAG_VIRTUAL = 32,
        GDNATIVE_EXTENSION_METHOD_FLAG_FROM_SCRIPT = 64,
        GDNATIVE_EXTENSION_METHOD_FLAG_VARARG = 128,
        GDNATIVE_EXTENSION_METHOD_FLAG_STATIC = 256,
        GDNATIVE_EXTENSION_METHOD_FLAGS_DEFAULT = GDNATIVE_EXTENSION_METHOD_FLAG_NORMAL,
    }
}
