namespace GDNative
{
    [NativeTypeName("unsigned int")]
    public enum GDNativeExtensionClassMethodArgumentMetadata : uint
    {
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_NONE,
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT8,
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT16,
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT32,
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64,
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT8,
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT16,
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT32,
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT64,
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_FLOAT,
        GDNATIVE_EXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_DOUBLE,
    }
}
